title: TECH2WIKI.COM
#description: 
repo: https://github.com/tech2wiki/tech2wiki-website/
url: https://tech2wiki.com
#baseurl: /tech2wiki-website
#lang: en
#direction: ltr
#highlighter: rouge

#theme: null

#google:
gtag: G-FR35BTGW9Q
#  adsense:

# debug:
#   compress: true
#   dist: false
#   shortcodes: true

readme_index:
  with_frontmatter: true

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions

exclude:
  - Makefile
  - CNAME
  - LICENSE
  - update.sh
  - Gemfile
  - Gemfile.lock
  - requirements.txt
  - node_modules
  - package.json
  - package-lock.json
  - webpack.config.js
  - jekyll-rtd-theme.gemspec
